version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  rufio-server:
    container_name: rufio-server-api
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      .env

    
  