version: '3'
services:
  nginx:
    ports:
      - "80:80"        
  rufio-server:
    volumes:
      - /app/node_modules
    environment:
      - /app/.env
      - NODE_ENV=production
    command: npm run expose
