version: '3'
services:
  nginx:
    ports:
      - "3001:80"
  rufio-server:
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

